### ISSUE TITLE
bug: "lte my_var = Table.foo" segfaults wren

### ISSUE THREAD

**Issue by jordanrfrazier** [kaskada-ai/kaskada#551]
**Description**
I made a typo creating a variable in fenl magic:
```
lte test = lookup(key, Table)
```

And it segfaulted Wren. 

**To Reproduce**
1. Run query with `lte` instead of `let`

**Actual Behavior**
panic!

**Expected Behavior**
Grammar parsing error 

**Relevant Logs / Links**
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x10078522c]

goroutine 575 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/Users/jordan.frazier/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.2.0/trace/span.go:244 +0x2c
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x1400036de00, {0x0, 0x0, 0x129e85348?})
	/Users/jordan.frazier/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.2.0/trace/span.go:283 +0x6f8
panic({0x101560be0, 0x102292a00})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x204
entgo.io/ent/dialect/sql.(*Predicate).mayWrap(0x1400041fd80, {0x1400031d7a0?, 0x2, 0x2}, 0x1400041fd80, {0x100fbe4a1, 0x3})
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/builder.go:1846 +0x26c
entgo.io/ent/dialect/sql.And.func1(0x1015bcd60?)
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/builder.go:1315 +0x40
entgo.io/ent/dialect/sql.(*Predicate).Query(0x1400041fd80)
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/builder.go:1811 +0xe4
entgo.io/ent/dialect/sql.(*Builder).join(0x14000805308, {0x140008052a0?, 0x1, 0x0?}, {0x0, 0x0})
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/builder.go:3353 +0x260
entgo.io/ent/dialect/sql.(*Builder).Join(...)
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/builder.go:3334
entgo.io/ent/dialect/sql.(*Selector).Query(0x140002bcf20)
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/builder.go:2704 +0xc04
entgo.io/ent/dialect/sql/sqlgraph.(*query).nodes(0x14000805568, {0x1017972b0, 0x1400054dda0}, {0x101798dc0, 0x14000666160})
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/sqlgraph/graph.go:564 +0x68
entgo.io/ent/dialect/sql/sqlgraph.QueryNodes({0x1017972b0, 0x1400054dda0}, {0x101798dc0?, 0x14000666160?}, 0x1400009e960)
	/Users/jordan.frazier/go/pkg/mod/entgo.io/ent@v0.11.1/dialect/sql/sqlgraph/graph.go:501 +0x7c
github.com/kaskada-ai/kaskada/wren/ent.(*KaskadaTableQuery).sqlAll(0x14000252e10, {0x1017972b0, 0x1400054dda0}, {0x0, 0x0, 0x0?})
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/ent/kaskadatable_query.go:570 +0x330
github.com/kaskada-ai/kaskada/wren/ent.(*KaskadaTableQuery).All(0x10151e100?, {0x1017972b0, 0x1400054dda0})
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/ent/kaskadatable_query.go:316 +0x68
github.com/kaskada-ai/kaskada/wren/internal.(*kaskadaTableClient).GetKaskadaTablesFromNames(0x0?, {0x1017972b0, 0x1400054dda0}, 0x14000485d40, {0x0, 0x0, 0xa6?})
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/internal/kaskada_table_client.go:257 +0x394
github.com/kaskada-ai/kaskada/wren/service.(*queryV1Service).CreateQuery(0x1400009f3e0, 0x140007fb700, {0x10179cd20, 0x1400023acc0})
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/service/query_v1.go:96 +0x41c
github.com/kaskada-ai/kaskada/gen/proto/go/kaskada/kaskada/v1alpha._QueryService_CreateQuery_Handler({0x1016c8d60?, 0x1400009f3e0}, {0x10179b0f8, 0x14000309d40})
	/Users/jordan.frazier/Documents/Datastax/kaskada/gen/proto/go/kaskada/kaskada/v1alpha/query_service_grpc.pb.go:149 +0xd4
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/validator.StreamServerInterceptor.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179b068?, 0x140007e53e0}, 0x1?, 0x10177e448)
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20211203031854-ed43ab3fa4f8/interceptors/validator/validator.go:111 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179b068?, 0x140007e53e0?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
github.com/grpc-ecosystem/go-grpc-middleware/auth.StreamServerInterceptor.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179b0b0, 0x1400054d8c0?}, 0x14000309980, 0x140007e4fa0)
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:66 +0x1d4
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179b0b0?, 0x1400054d8c0?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.StreamServerInterceptor.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179b0b0, 0x1400054d4d0}, 0x14000309980, 0x140007e4fc0)
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20211203031854-ed43ab3fa4f8/interceptors/server.go:35 +0x224
github.com/kaskada-ai/kaskada/wren/telemetry.(*loggingProvider).StreamPayloadInterceptor(0x14000666000, {0x1016c8d60, 0x1400009f3e0}, {0x10179b0b0, 0x1400054d4d0}, 0x30?, 0x14000076900?)
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/telemetry/logging.go:121 +0x260
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179b0b0?, 0x1400054d4d0?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.StreamServerInterceptor.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179c190, 0x1400054d380}, 0x14000309980, 0x140007e4fe0)
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20211203031854-ed43ab3fa4f8/interceptors/server.go:35 +0x224
github.com/kaskada-ai/kaskada/wren/telemetry.(*loggingProvider).StreamInterceptor(0x14000666000, {0x1016c8d60, 0x1400009f3e0}, {0x10179c190, 0x1400054d380}, 0x1400054d380?, 0x0?)
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/telemetry/logging.go:116 +0x200
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179c190?, 0x1400054d380?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
github.com/kaskada-ai/kaskada/wren/telemetry.(*tracingProvider).StreamInterceptor(0x0?, {0x1016c8d60, 0x1400009f3e0}, {0x10179b380?, 0x1400054d2f0?}, 0x30?, 0x140007e5040)
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/telemetry/tracing.go:109 +0xbc
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179b380?, 0x1400054d2f0?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179b188, 0x14000309998}, 0x14000309980, 0x140007e5060)
	/Users/jordan.frazier/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.26.1/interceptor.go:412 +0x4c4
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179b188?, 0x14000309998?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179b4a0?, 0x140004b4380}, 0x30?, 0x140007e5080)
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0x10c
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x1016c8d60?, 0x1400009f3e0?}, {0x10179b4a0?, 0x140004b4380?})
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3c
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1({0x1016c8d60, 0x1400009f3e0}, {0x10179b4a0, 0x140004b4380}, 0x1014735e0?, 0x1400078d2c0?)
	/Users/jordan.frazier/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58 +0xb8
google.golang.org/grpc.(*Server).processStreamingRPC(0x140006805a0, {0x10179e2a0, 0x140007a4680}, 0x140004859e0, 0x14000496e70, 0x102298720, 0x0)
	/Users/jordan.frazier/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1627 +0xf30
google.golang.org/grpc.(*Server).handleStream(0x140006805a0, {0x10179e2a0, 0x140007a4680}, 0x140004859e0, 0x0)
	/Users/jordan.frazier/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1708 +0x804
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/jordan.frazier/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/jordan.frazier/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x290
exit status 2
make: *** [wren/run] Error 1
```

**Comment by bjchambers** [comment]
Interesting. Any details on what it does within Sparrow? I'd expect it to be an error or panic (it expects you're calling the `lte` function, rather than starting a `let` expression).

**Comment by jordanrfrazier** [comment]
> 

Yeah,

**Comment by jordanrfrazier** [comment]
Unfortunately don't see any changes with the internal error change reverted. 

The offending panic is 
```
github.com/kaskada-ai/kaskada/wren/internal.(*kaskadaTableClient).GetKaskadaTablesFromNames(0x0?, {0x1017f7950, 0x140006bd590}, 0x140006bab40, {0x0, 0x0, 0xa6?})
	/Users/jordan.frazier/Documents/Datastax/kaskada/wren/internal/kaskada_table_client.go:258 +0x3c4
```
Which is:
```
	kaskadaTables, err := owner.QueryKaskadaTables().Where(kaskadatable.Or(predicates...)).All(ctx)
	if err != nil {
		subLogger.Error().Err(err).Msg("issue getting tables")
		return nil, err
	}
```

But I don't see any recent changes here or in the `ent` files.

**Comment by jordanrfrazier** [comment]
Another recent commit that touches table files is possible https://github.com/kaskada-ai/kaskada/pull/472/commits, but this one is harder to revert to verify. I'll check with @epinzur next week to see if he has insights on this.

**Comment by epinzur** [comment]
i've seen wren panic in a similar way a few times recently, but I wasn't able to lock down a repeatable test case.  I can look into this now.

**Comment by epinzur** [comment]
okay, I'm pretty sure this PR introduced the bug: https://github.com/kaskada-ai/kaskada/pull/448

compare: https://github.com/kaskada-ai/kaskada/commit/c00329c8665a93f1ba9f941058722d73bc436225#diff-9d4dcadebd10f9c7d6028698cc11f5b485093c9fe2daaed92ecafbf7a76395f0

new lines 92-111 in `wren/service/query_v1.go` throw a panic if the query compilation fails.  instead these lines should be after the compile validation check: ```
if compileResponse.Plan == nil {
		responseStream.Send(&v1alpha.CreateQueryResponse{
			State:   v1alpha.CreateQueryResponse_STATE_FAILURE,
			Metrics: metrics,
		})
		subLogger.Debug().Msg("returning because compile plan is nil")
		return nil
	}
```

**Comment by epinzur** [comment]
Jordan can you see if the code on `wren/fix_panic` branch fixes your issue?
