### ISSUE TITLE
Loading parquet sources with Float timestamp is broken

### ISSUE THREAD

**Issue by epinzur** [kaskada-ai/kaskada#776]
getting:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: failed to prepare batch
├╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-session/src/table.rs:150:14](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-session/src/table.rs:150:14)
│
├─▶ internal error
│   ╰╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare/preparer.rs:122:18](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare/preparer.rs:122:18)
│
├─▶ failed to create Parquet file reader
│   ╰╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:79:18](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:79:18)
│
╰─▶ Internal error
    ├╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:78:18](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:78:18)
    ╰╴Expected column 'ts' to be castable to Timestamp(Nanosecond, None), but Float64 was not', src/table.rs:95:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
RustPanic                                 Traceback (most recent call last)
[/var/folders/_7/czrlt9jx79n78l_zsyfwycs40000gp/T/ipykernel_50657/1098232920.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/_7/czrlt9jx79n78l_zsyfwycs40000gp/T/ipykernel_50657/1098232920.py) in <cell line: 1>()
      2 # Use the "ts" column as the time associated with each row,
      3 # and the "channel" column as the entity associated with each row.
----> 4 messages = await kd.sources.Parquet.create(
      5     path = "slack-export/messages.parquet",
      6     time_column = "ts",

[~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/beep-gpt/~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py) in create(path, time_column, key_column, schema, subsort_column, grouping_name, time_unit)
    579 
    580         if path:
--> 581             await source.add_file(path)
    582         return source
    583 

[~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/beep-gpt/~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py) in add_file(self, path)
    586         path = Source._get_absolute_path(path)
    587 
--> 588         await self._ffi_table.add_parquet(path)

RustPanic: rust future panicked
```

**Comment by kerinin** [comment]
Blocked on #776

**Comment by bjchambers** [comment]
I suspect this is broken because Parquet sources use the old prepare logic, rather than the prepare code we threw together for preparing Pandas / PyArrow data. We either need to fix the old prepare code, or switch it to using the new / simpler prepare logic.

**Comment by jordanrfrazier** [comment]
Yeah, could probably just do a small hack here that casts floats to ints first, then to timestamps. I worry about the cross-usage of the old prepare code with the newer prepare code. I think it's going to slowly bloat again as we work on parity, but we'd have to spend some time to redesign prepare to be a bit cleaner. 

https://github.com/kaskada-ai/kaskada/blob/88de931e2df5b0d073baf3326dde1f86dcb609f4/crates/sparrow-runtime/src/prepare/prepare_input_stream.rs#L45
