### ISSUE TITLE
bug: NPE in Manager during CreateQuery

### ISSUE THREAD

**Issue by jordanrfrazier** [kaskada-ai/kaskada#82]
**Description**
NPE in Manager during create query

**To Reproduce**
1. Spin up notebook per instructions in readme

**Actual Behavior**
NPE

**Expected Behavior**
Successful Query

**Relevant Logs / Links**
```
~/.cache/kaskada/logs docker exec bf55794d872f cat  .cache/kaskada/logs/2bff0716-c3e3-4581-9620-401f2532e165/api_logs.txt    
{"level":"info","time":"2023-03-06T21:33:41Z","message":"Starting api..."}
{"level":"info","time":1678138421,"message":"using in-memory sqlite as backing store"}
{"level":"warn","time":1678138421,"message":"sqlite backing store currently doesn't support parallel operation.  setting all parallization factors to 1."}
{"level":"info","port":9100,"time":1678138421,"message":"metrics is online"}
{"level":"info","port":6666,"time":1678138421,"message":"gRPC-health server is online"}
{"level":"info","grpcPort":50051,"time":1678138421,"message":"gRPC server is online"}
{"level":"info","port":8080,"time":1678138421,"message":"gRPC-gateway is online"}
{"level":"info","grpc.component":"server","grpc.method":"CreateTable","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"24346babdf25b1a239dc6ccf8842c3ee","grpc.start_time":"2023-03-06T21:33:44Z","grpc.code":"OK","grpc.time_ms":"0.864","time":1678138424,"message":"started call"}
{"level":"info","grpc.component":"server","grpc.method":"CreateTable","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"24346babdf25b1a239dc6ccf8842c3ee","grpc.code":"OK","grpc.time_ms":"0.267","grpc.request.content":"{\"table\":{\"tableName\":\"transactions\",\"timeColumnName\":\"transaction_time\",\"entityKeyColumnName\":\"id\"}}","time":1678138424,"message":"started call"}
{"level":"info","grpc.component":"server","grpc.method":"CreateTable","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"24346babdf25b1a239dc6ccf8842c3ee","grpc.code":"OK","grpc.time_ms":"39.336","grpc.response.content":"{\"table\":{\"tableId\":\"6ccd6ad5-97de-49e5-af70-f23a4a1e0fb9\",\"tableName\":\"transactions\",\"timeColumnName\":\"transaction_time\",\"entityKeyColumnName\":\"id\",\"createTime\":\"2023-03-06T21:33:44.640318Z\",\"updateTime\":\"2023-03-06T21:33:44.640358Z\",\"tableSource\":{\"kaskada\":{}}}}","time":1678138424,"message":"finished call"}
{"level":"info","grpc.component":"server","grpc.method":"CreateTable","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"24346babdf25b1a239dc6ccf8842c3ee","grpc.start_time":"2023-03-06T21:33:44Z","grpc.code":"OK","grpc.time_ms":"44.749","time":1678138424,"message":"finished call"}
{"level":"info","grpc.component":"server","grpc.method":"LoadData","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"02bea4e23e4e065c77de65908116262d","grpc.start_time":"2023-03-06T21:33:44Z","grpc.code":"OK","grpc.time_ms":"0.098","time":1678138424,"message":"started call"}
{"level":"info","grpc.component":"server","grpc.method":"LoadData","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"02bea4e23e4e065c77de65908116262d","grpc.code":"OK","grpc.time_ms":"0.151","grpc.request.content":"{\"tableName\":\"transactions\",\"fileInput\":{\"fileType\":\"FILE_TYPE_PARQUET\",\"uri\":\"file:///home/jovyan/transactions_part1.parquet\"}}","time":1678138424,"message":"started call"}
{"level":"info","grpc.component":"server","grpc.method":"LoadData","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"02bea4e23e4e065c77de65908116262d","grpc.code":"OK","grpc.time_ms":"56.410","grpc.response.content":"{\"dataTokenId\":\"6d7124aa-7c26-4f16-b690-5a828bffea18\"}","time":1678138424,"message":"finished call"}
{"level":"info","grpc.component":"server","grpc.method":"LoadData","grpc.method_type":"unary","grpc.service":"kaskada.kaskada.v1alpha.TableService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"02bea4e23e4e065c77de65908116262d","grpc.start_time":"2023-03-06T21:33:44Z","grpc.code":"OK","grpc.time_ms":"58.033","time":1678138424,"message":"finished call"}
{"level":"info","grpc.component":"server","grpc.method":"CreateQuery","grpc.method_type":"server_stream","grpc.service":"kaskada.kaskada.v1alpha.QueryService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"96a9e3c64a7438343919f833bbdb067d","grpc.start_time":"2023-03-06T21:33:53Z","grpc.code":"OK","grpc.time_ms":"2.771","time":1678138433,"message":"started call"}
{"level":"info","grpc.component":"server","grpc.method":"CreateQuery","grpc.method_type":"server_stream","grpc.service":"kaskada.kaskada.v1alpha.QueryService","peer.address":"127.0.0.1:50186","protocol":"grpc","request_id":"96a9e3c64a7438343919f833bbdb067d","grpc.code":"OK","grpc.time_ms":"2.937","grpc.request.content":"{\"query\":{\"expression\":\"transactions\",\"resultBehavior\":\"RESULT_BEHAVIOR_FINAL_RESULTS\",\"limits\":{}},\"queryOptions\":{\"streamMetrics\":true,\"presignResults\":true}}","time":1678138433,"message":"started call"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1386ed1]

goroutine 145 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/home/runner/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.2.0/trace/span.go:244 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0000bb680, {0x0, 0x0, 0x415fff?})
	/home/runner/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.2.0/trace/span.go:283 +0x8ad
panic({0x163c9a0, 0x26ece40})
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x212
github.com/kaskada-ai/kaskada/wren/service.(*queryV1Service).validateOutputTo(0x1c49550?, {0x1c49550?, 0xc0000de990?}, 0xc0000bd400)
	/home/runner/work/kaskada/kaskada/wren/service/query_v1.go:394 +0x2b1
github.com/kaskada-ai/kaskada/wren/service.(*queryV1Service).CreateQuery(0xc0007588d0, 0xc0000f2340, {0x1c4ef80, 0xc0000fcab0})
	/home/runner/work/kaskada/kaskada/wren/service/query_v1.go:65 +0x3e6
github.com/kaskada-ai/kaskada/gen/proto/go/kaskada/kaskada/v1alpha._QueryService_CreateQuery_Handler({0x178bf40?, 0xc0007588d0}, {0x1c4d358, 0xc00082dcf8})
	/home/runner/work/kaskada/kaskada/gen/proto/go/kaskada/kaskada/v1alpha/query_service_grpc.pb.go:143 +0xd0
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/validator.StreamServerInterceptor.func1({0x178bf40, 0xc0007588d0}, {0x1c4d2c8?, 0xc000375020}, 0x1783180?, 0x18ecb10)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20211203031854-ed43ab3fa4f8/interceptors/validator/validator.go:111 +0x9a
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4d2c8?, 0xc000375020?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/auth.StreamServerInterceptor.func1({0x178bf40, 0xc0007588d0}, {0x1c4d310, 0xc0000de720?}, 0xc00082dae8, 0xc000374c60)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:66 +0x1db
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4d310?, 0xc0000de720?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.StreamServerInterceptor.func1({0x178bf40, 0xc0007588d0}, {0x1c4d310, 0xc0000de690}, 0xc00082dae8, 0xc000374c80)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20211203031854-ed43ab3fa4f8/interceptors/server.go:35 +0x31e
github.com/kaskada-ai/kaskada/wren/telemetry.(*loggingProvider).StreamPayloadInterceptor(0xc0003086c0, {0x178bf40, 0xc0007588d0}, {0x1c4d310, 0xc0000de690}, 0x30?, 0xc000180800?)
	/home/runner/work/kaskada/kaskada/wren/telemetry/logging.go:99 +0x303
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4d310?, 0xc0000de690?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.StreamServerInterceptor.func1({0x178bf40, 0xc0007588d0}, {0x1c4e3f0, 0xc0000de600}, 0xc00082dae8, 0xc000374ca0)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20211203031854-ed43ab3fa4f8/interceptors/server.go:35 +0x31e
github.com/kaskada-ai/kaskada/wren/telemetry.(*loggingProvider).StreamInterceptor(0xc0003086c0, {0x178bf40, 0xc0007588d0}, {0x1c4e3f0, 0xc0000de600}, 0xc0000de600?, 0x0?)
	/home/runner/work/kaskada/kaskada/wren/telemetry/logging.go:94 +0x2ae
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4e3f0?, 0xc0000de600?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
github.com/kaskada-ai/kaskada/wren/telemetry.(*tracingProvider).StreamInterceptor(0x0?, {0x178bf40, 0xc0007588d0}, {0x1c4d598?, 0xc0000de570?}, 0x30?, 0xc000374cc0)
	/home/runner/work/kaskada/kaskada/wren/telemetry/tracing.go:109 +0x112
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4d598?, 0xc0000de570?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamServerInterceptor.func1({0x178bf40, 0xc0007588d0}, {0x1c4d3e8, 0xc00082db30}, 0xc00082dae8, 0xc000374ce0)
	/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.26.1/interceptor.go:412 +0x673
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4d3e8?, 0xc00082db30?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1({0x178bf40, 0xc0007588d0}, {0x1c4d6b8?, 0xc000840ee0}, 0x4063759be0?, 0xc000374d00)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:121 +0x109
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x178bf40?, 0xc0007588d0?}, {0x1c4d6b8?, 0xc000840ee0?})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1({0x178bf40, 0xc0007588d0}, {0x1c4d6b8, 0xc000840ee0}, 0x15511e0?, 0xc000259640?)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58 +0xbe
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0004805a0, {0x1c50300, 0xc000093860}, 0xc000482b40, 0xc000758ba0, 0x26f29e0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1627 +0x11c6
google.golang.org/grpc.(*Server).handleStream(0xc0004805a0, {0x1c50300, 0xc000093860}, 0xc000482b40, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1708 +0x9ea
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
```

**Comment by kevinjnguyen** [comment]
Since this was resolved with #83. I'll go ahead and close this. Feel free to open again if we need to review.
